Делает домашнее задание раздела 4
htmlacademy-javascript/1953987-kekstagram-simple-27 pull request #3
Opened 2022-10-12 14:52 UTC by MarinaDobrusina

2022-10-12 18:12 UTC, o-bender requested changes

2022-10-12 18:12 UTC, o-bender commented on js/main.js
> +const photoObject = () => Array.from({
Это функция, а значит в имени должен быть глагол

2022-10-12 18:12 UTC, o-bender commented on js/main.js
> +const getIndexUrl = () => {
Эта функция завершится исключением о превышении глубины рекурсии если количество вызовов будет превышать 25.

2022-10-12 18:12 UTC, o-bender commented on js/main.js
> +const getIndexId = () => {
Эта функция завершится исключением о превышении глубины рекурсии если количество вызовов будет превышать 25.

2022-10-12 18:12 UTC, o-bender commented on js/main.js
> +const createPhotoObject = () => ({
В callback метода Array.from передаются несколько параметров. Один из которых порядковый номер элемента из исходного массива. Т.е. сигнатура такая:
```
Array.from({length: PHOTO_OBJECT_COUNT}, (arrayElement, index) => ...)
```
Где arrayElement это последовательно каждый элемент исходного массива, а index это номер элемента начиная с 0. Так что есть смысл использовать именно этот index в качестве id. Да и в качестве номера картинки для url.

2022-10-12 18:12 UTC, o-bender commented on js/main.js
> +const checkStringLength = (string, length) => string.length <= length;
Эту функцию можно смело удалять. Она нам никогда не понадобится.

2022-10-12 18:12 UTC, o-bender commented on js/main.js
> +getRandomIntInclusive(1.78, 6.23);
Этот вызов тоже можно удалить. Просто так искать какое-то число тоже смысла особого нет. А когда необходимость в getRandomIntInclusive пропадёт, то мы и её удалим.

2022-10-12 18:12 UTC, o-bender commented on js/main.js
> +const PHOTO_OBJECT_COUNT = 25;
Константы надо определять в самом верху файла сразу после секции import. Т.е. сейчас пока что просто в самом верху файла.

2022-10-13 19:23 UTC, o-bender requested changes

2022-10-13 19:23 UTC, o-bender commented on js/main.js
> +const getPhotoObject = () => Array.from({
Давай лучше назовём createPhotos. Потому что:
1. Функция совершает create, а не get.
2. Создаёт несколько фотографий, а значит множественное число.
3. Не надо указывать тип данных в именах переменных и функций.

2022-10-13 19:41 UTC, MarinaDobrusina commented on js/main.js
> +const getPhotoObject = () => Array.from({
Получается и const createPhotoObject тоже стоит переназвать?

2022-10-13 19:42 UTC, MarinaDobrusina commented on js/main.js
> +const getPhotoObject = () => Array.from({
Но нормально, если будет createPhotos и createPhoto? Две разных функции, но названия уж очень похожи.

2022-10-14 07:51 UTC, o-bender commented on js/main.js
> +const getPhotoObject = () => Array.from({
Не просто нормально, а прям хорошо :) Мы ж читать умеем, букву S не пропустим, и то что они похожи наоборот подчёркивает общий контекст их применения.

2022-10-14 08:11 UTC, merged