Выполняет домашнее задание 7 модуля
htmlacademy-javascript/1953987-kekstagram-simple-27 pull request #5
Opened 2022-10-24 10:44 UTC by MarinaDobrusina

2022-10-25 08:16 UTC, o-bender requested changes

2022-10-25 08:16 UTC, o-bender commented on js/thumbnails.js
> +thumbnailsCollection.forEach(({
анонимную функцию внутри forEach надо вынести в область видимости модуля и дать ей имя что-нибудь вроде renderThumbnail

2022-10-25 08:16 UTC, o-bender commented on js/thumbnails.js
> +const thumbnailsCollection = createPhotos();
Эту строку надо перенести в main.js

2022-10-25 08:16 UTC, o-bender commented on js/thumbnails.js
> +const thumbnailsFragment = document.createDocumentFragment();
Раз ты используешь метод append (вот тут `thumbnailsFragment.append`), то нет нужды использовать DocumentFragment. Проще воспользоваться методом map и деструктуризацией.
Вот эту строку:
```
thumbnailsContainer.append(...photos.map(renderThumbnail));
```
Надо поместить в функцию renderThumbnails(photos). Экспортировать и вызывать её в main.js.

2022-10-25 08:16 UTC, o-bender commented on js/thumbnails.js
> +  thumbnailsFragment.append(thumbnailElement);
Вместо этой строки просто сделай `return thumbnailElement;`. Такой подход упростит твой код и сделает функцию независимой от внешних переменных.

2022-10-25 10:28 UTC, MarinaDobrusina commented on js/thumbnails.js
> +const thumbnailsFragment = document.createDocumentFragment();
Вот тут не очень поняла, если я выделяю анонимную функцию отдельно, она начинает выглядеть так:
const renderThumbnail = ({
  url,
  likes,
  comments,
}) => {
  const thumbnailElement = thumbnailTemplate.cloneNode(true);
  thumbnailElement.querySelector('.picture__img').src = url;
  thumbnailElement.querySelector('.picture__likes').textContent = likes;
  thumbnailElement.querySelector('.picture__comments').textContent = comments;
  thumbnailsFragment.append(thumbnailElement);
  return thumbnailElement;
};
тогда в какое место тут я должна добавить (photos) и что это вообще такое?

2022-10-25 10:29 UTC, MarinaDobrusina commented on js/thumbnails.js
> +const thumbnailsCollection = createPhotos();
Зачем?

2022-10-26 09:08 UTC, o-bender commented on js/thumbnails.js
> +const thumbnailsCollection = createPhotos();
Затем, что работа приложения должна строиться по принципу пирамиды. Вершина это main.js. В нём мы запускаем наше приложение и дальше с помощью цепочек import и export мы вызываем другие функции. Если же мы будем бесконтрольно исполнять код внутри модуля, то:
- Мы не сможем синхронизировать выполнение кода в модулях. Т.е. мы даже не сможем спрогнозировать какой модуль выполнится первым, а какой последним.
- Мы не сможем повторно использовать код в модулях. Он один раз выполнится и всё.
- Такой код практически невозможно протестировать.
- Такой код если в нём есть ресурсоёмкие операции может приводить к зависанию браузера.
- Простыня не структурированного кода нечитабельна. У функций есть имя, строго опередённые артументы, возвращаемые значения. и как правило описание.

2022-10-26 09:12 UTC, o-bender commented on js/thumbnails.js
> +const thumbnailsFragment = document.createDocumentFragment();
`createPhotos()` создаёт фотографии. Но почему-то они превращаются в `const thumbnailsCollection = createPhotos();`. И как я написал, не надо использовать DocumentFragmert. 
```
const renderThumbnails = (photos) => thumbnailsContainer.append(...photos.map(renderThumbnail));
```
и уже в main.js
```
const photos = createPhotos();
renderThumbnails(photos);
```

2022-10-26 09:13 UTC, o-bender commented on js/thumbnails.js
> +const thumbnailsFragment = document.createDocumentFragment();
Для вставки кода в комментарии используй блок для форматирования кода.

2022-10-26 15:41 UTC, merged