пишет модуль для редактирования масштаба изображения
htmlacademy-javascript/1953987-kekstagram-simple-27 pull request #7
Opened 2022-11-06 16:51 UTC by MarinaDobrusina

2022-11-06 19:39 UTC, o-bender requested changes

2022-11-06 19:39 UTC, o-bender commented on js/scale.js
> +const currentValue = parseInt(inputValueScaleElement.value, 10);
Не надо парсить значение из верстки. Т.к. верстальщик скорей всего вообще не понимает бизнес процесса. И в верстке может быть какое угодно значение, вплоть до абракадабры. Ты как программист ответственна за описание бизнес логики.

2022-11-06 19:39 UTC, o-bender commented on js/scale.js
> +const STEP_SCALE = 25;
Константы должны идти сразу после импортов.

2022-11-06 19:39 UTC, o-bender commented on js/form.js
> +const imageElement = document.querySelector('.img-upload__preview img');
В этом файле эта переменная вообще не используется. Её стоит перенести в scale.js.

2022-11-06 19:39 UTC, o-bender commented on js/scale.js
> +const smallerButtonElement = formElement.querySelector('.scale__control--smaller');
Напиши лучше `document.querySelector('.scale__control--smaller')`. Тогда и formElement не надо будет экспортировать и импортировать.

2022-11-06 19:39 UTC, o-bender commented on js/scale.js
> +const smallerButtonElement = formElement.querySelector('.scale__control--smaller');
![image](https://user-images.githubusercontent.com/6534704/200191218-438cb0c4-9d37-4daa-ab03-5f2471efd2e4.png)

2022-11-06 19:39 UTC, o-bender commented on js/scale.js
> +const smallerButtonElement = formElement.querySelector('.scale__control--smaller');
Это последствие так называемого сайд эффекта. Т.е. проблемы синхронизации частей кода не обёрнутого функциями и выполняемого сразу при загрузке модуля. Импортируемая переменная ещё не инициализирована и при попытке доступа к ней получаем ошибку. 
Выводы: 
1. Если используешь переменные в области видимости модуля, не пытайся их экспортировать.
2. Заглядывай в консоль браузера.)

2022-11-07 12:50 UTC, MarinaDobrusina commented on js/scale.js
> +const currentValue = parseInt(inputValueScaleElement.value, 10);
а как тогда быть здесь?

2022-11-07 13:14 UTC, MarinaDobrusina commented on js/scale.js
> +const currentValue = parseInt(inputValueScaleElement.value, 10);
а как тогда сделать?

2022-11-08 14:10 UTC, o-bender commented on js/effect.js
> +const EFFECT = {
EFFECTS - измени на множественное число

2022-11-08 14:10 UTC, o-bender commented on js/effect.js
> +const onFormChange = (evt) => {
onFormChange и updateSlider это по сути одна функция. Логика изменения эффекта разделена на две функции, так что мб было бы удобней их объединить.
И что бы уйти от переменной chosenEffect в области видимости модуля, стоит просто передать chosenEffect как аргумент.
```
const updateSlider = (chosenEffect) => и т.д.

const onFormChange = (evt) => {
  if (!evt.target.classList.contains('effects__radio')) {
    return;
  }
  const chosenEffect = EFFECT[evt.target.value];
  imageElement.classList.add(`effects__preview--${evt.target.value}`);
  updateSlider(chosenEffect);
};
```

2022-11-08 14:10 UTC, o-bender commented on js/effect.js
> +  imageElement.style.filter = `${chosenEffect.style}(${sliderValue}${chosenEffect.unit})`;
Что бы уйти от глобальной переменной chosenEffect. Можно получать из dom текущий активный элемент:
```
const checkedRadioElement = document.querySelector('.effects__radio:checked');
const chosenEffect = EFFECT[checkedRadioElement.value];
```

2022-11-08 14:10 UTC, o-bender commented on js/effect.js
> +formElement.addEventListener('change', (onFormChange));
Лишние скобки

2022-11-08 15:17 UTC, merged