Выпонляет домашнее задание модуля 11
htmlacademy-javascript/1953987-kekstagram-simple-27 pull request #8
Opened 2022-11-11 13:03 UTC by MarinaDobrusina

2022-11-11 13:35 UTC, o-bender requested changes

2022-11-11 13:35 UTC, o-bender commented on js/api.js
> +    .then((response) => response.json())
Добавь проверку response.ok

2022-11-11 13:35 UTC, o-bender commented on js/api.js
> +      if (response.ok) {
Как бы не ошибка. Но стилистически обычно пишут так:
```
if (response.ok) {
    onSuccess();
    return;
}

onFail();
```

2022-11-11 13:35 UTC, o-bender commented on js/main.js
> +}, () => showAlert('Не удалось получить данные с сервера. Попробуйте перезагрузить страницу.'));
Ты передаёшь в этой строке текст ошибки, но в тоже время ещё и тут:
```
   .catch(() => {
      onFail('Не удалось получить данные с сервера. Попробуйте перезагрузить страницу.');
    });
```
Я бы написал так:
```
getData((photos) => renderThumbnails(photos), showAlert);
```

2022-11-11 13:35 UTC, o-bender commented on js/main.js
> +// import {
Лишние комментарии удали

2022-11-11 13:35 UTC, o-bender commented on js/form.js
> +  inputValueScaleElement,
1. Не надо шарить переменные между модулями. Добром не кончится.
2. Эта переменная используется только в scale.js. Есть смысл просто её туда перенести.

2022-11-11 13:35 UTC, o-bender commented on js/form.js
> +        () => addErrorMessage(),
Лишняя обёртка: `() => addErrorMessage(),`
Лучше так: `addErrorMessage,`

2022-11-11 13:35 UTC, o-bender commented on js/form-message.js
> +  successElement.style = 'z-index: 2';
Так не надо, это рано или поздно приведёт к какой-нибудь ошибке.
Пиши так: `successElement.style.zIndex = 2;`

2022-11-11 13:35 UTC, o-bender commented on js/form-message.js
> +  document.addEventListener('keydown', onModalEscKeydown);
Не удаляешь этот слушатель. И они продолжают прослушивать события после удаления модального окна. И с каждым новым окном создаётся ещё один слушатель.
![image](https://user-images.githubusercontent.com/6534704/201351006-8ce9efeb-c54f-4c17-bda1-b248c8102c13.png)

2022-11-11 13:35 UTC, o-bender commented on js/form-message.js
> +const bodyElement = document.querySelector('body');
Можно просто писать `document.body`.
```
document.body.querySelector('.some-class')
```

2022-11-11 13:35 UTC, o-bender commented on js/form-message.js
> +const addSuccessMessage = () => {
Полная копия addErrorMessage)

2022-11-11 13:35 UTC, o-bender commented on js/form-message.js
> +    bodyElement.querySelector('.success').remove();
Раз уж пишем функции внутри функций, то давай пользоваться замыканиями по полной:
```
successElement.remove();
```

2022-11-11 13:35 UTC, o-bender commented on js/form-message.js
> +  window.addEventListener('click', onWindowClick);
Та же самая история, что с `document.addEventListener('keydown', onModalEscKeydown);`.

2022-11-12 10:44 UTC, MarinaDobrusina commented on js/form-message.js
> +  successElement.style = 'z-index: 2';
если пишу так, как ты сказал, то окно не появляется и в консоле вылезает ошибка: TypeError: can't access property "zIndex", errorElement.style is undefined  (ну это я такую же запись, но в addErrorMessage изменила)

2022-11-12 10:44 UTC, MarinaDobrusina commented on js/form-message.js
> +  successElement.style = 'z-index: 2';
Если меняю значение на successElement, то он загружает сообдщение об ошибке загрузки, хотя данные отправляются и все норм.

2022-11-12 10:44 UTC, MarinaDobrusina commented on js/form-message.js
> +const addSuccessMessage = () => {
ну не совсем, элементы-то другие задействованы)

2022-11-12 10:44 UTC, MarinaDobrusina commented on js/form-message.js
> +    bodyElement.querySelector('.success').remove();
я так и написала сначала, но в консоле получила: Uncaught TypeError: successElement.remove is not a function

2022-11-12 10:44 UTC, MarinaDobrusina commented on js/form-message.js
> +    bodyElement.querySelector('.success').remove();
еще я пробовала так написать:
successElement.parentNode.removeChild(successElement);
но это тоже не дало результата(

2022-11-12 11:17 UTC, o-bender commented on js/form-message.js
> +  successElement.style = 'z-index: 2';
Это ещё одна причина почему всегда надо использовать такую `style.zIndex` нотацию. Т.к. при такой нотации не получится прикрыть баг.
![image](https://user-images.githubusercontent.com/6534704/201470672-b2b2e1e5-331a-4abb-b4da-28d61228a37d.png)
Обрати внимание на скриншоте видно, что в `successElement.style` undefined. Потому, что после клонирования ты получила не `.success` элемент. А фрагмент внутри которого есть дочерний элемент `.success`. А фрагмент это просто временный контейнер не имеющий атрибута style.
По этому надо либо до, либо после клонирования обратиться к `.success` и работать уже с ним.
Т.е. либо так:
```
const successTemplate = document.querySelector('#success').content.querySelector('.success');
```
либо так:
```
const successElement = successTemplate.cloneNode(true).querySelector('.success');
```
На мой взгляд, первый вариант удобней.

Теперь исходя из всего можно придти к выводу, что раз ты изначально присваивала z-index несуществующему элементу (фрагменту), следовательно он никогда не работал. Получается, что это присваивание в принципе лишнее.
Но если возникает проблема с тем, что модальное окно находится слишком низко по оси Z, то правильней будет поправить CSS и не тянуть работу со стилем в бизнес логику.

2022-11-12 11:17 UTC, o-bender commented on js/form-message.js
> +    bodyElement.querySelector('.success').remove();
Правильно. Ответ почему так в комментарии про z-index.

2022-11-12 11:17 UTC, o-bender commented on js/form-message.js
> +const addSuccessMessage = () => {
Меньше кода - меньше багов. =)
Я не призываю бежать и переделывать, на это есть косвенный критерий, но он дополнительный и его можно оспорить. Так что проблем проверяющий не доставит.
Но. Цель ведь не ачивку получить? Цель понять и научиться делать хорошо.
Попробуй как время будет обобщить эту функцию.

==== Спойлер ====

Я бы обобщил так:
```
const errorTemplate = document.body.querySelector('#error').content.querySelector('.error');
const successTemplate = document.body.querySelector('#success').content.querySelector('.success');

const showMessage = (template, rootClass) => {
  const messageElement = template.cloneNode(true);
  const button = messageElement.querySelector(`.{rootClass}__button`);

  const deleteMessage = () => {
    messageElement.remove();
    document.removeEventListener('keydown', onModalEscKeydown);
    window.removeEventListener('click', onWindowClick);
  };

  function onModalEscKeydown (evt) {
    if (isEscapeKey(evt)) {
      deleteMessage();
    }
  }

  function onWindowClick (evt) {
    if (evt.target === messageElement) {
      deleteMessage();
    }
  }

  errorButton.addEventListener('click', deleteMessage);
  document.addEventListener('keydown', onModalEscKeydown);
  window.addEventListener('click', onWindowClick);

  document.body.append(messageElement);
};

const showSuccessMessage = () => showMessage(sucessTemplate, 'success');
const showErrorMessage = () => showMessage(errorTemplate, 'error');
```

2022-11-12 12:31 UTC, merged